export enum RoutesPath {
  Initial = '/',
  Other = '*',
  Login = '/login',
  Signup = '/signup',
  Main = '/main',
  Projects = '/projects',
  Cvs = '/cvs',
  Departments = '/departments',
  Positions = '/positions',
  Skills = '/skills',
  Languages = '/languages',
  EmployeeProfile = '/employees/:id/profile',
  EmployeeSkills = '/employees/:id/skills',
  Employee_languages = '/employees/:id/languages',
  EmployeeCvs = '/employees/:id/cvs',
}
